/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as CrewRouteImport } from './routes/crew'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AppRouteImport } from './routes/app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CrewIndexRouteImport } from './routes/crew.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as CrewScheduleRouteImport } from './routes/crew.schedule'
import { Route as AppWindowsRouteImport } from './routes/app.windows'
import { Route as AppTeamRouteImport } from './routes/app.team'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppScheduleRouteImport } from './routes/app.schedule'
import { Route as AppRevenueRouteImport } from './routes/app.revenue'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppProjectsRouteImport } from './routes/app.projects'
import { Route as AppProducersRouteImport } from './routes/app.producers'
import { Route as AppFinanciersRouteImport } from './routes/app.financiers'
import { Route as AppExpensesRouteImport } from './routes/app.expenses'
import { Route as AppDistributorsRouteImport } from './routes/app.distributors'
import { Route as AppDistributionRouteImport } from './routes/app.distribution'
import { Route as AppComplianceRouteImport } from './routes/app.compliance'
import { Route as AppBudgetsRouteImport } from './routes/app.budgets'
import { Route as AppAssetsRouteImport } from './routes/app.assets'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppActivityRouteImport } from './routes/app.activity'
import { Route as AppProjectsIdRouteImport } from './routes/app.projects.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const CrewRoute = CrewRouteImport.update({
  id: '/crew',
  path: '/crew',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrewIndexRoute = CrewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CrewRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const CrewScheduleRoute = CrewScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => CrewRoute,
} as any)
const AppWindowsRoute = AppWindowsRouteImport.update({
  id: '/windows',
  path: '/windows',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppRevenueRoute = AppRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppProducersRoute = AppProducersRouteImport.update({
  id: '/producers',
  path: '/producers',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanciersRoute = AppFinanciersRouteImport.update({
  id: '/financiers',
  path: '/financiers',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppDistributorsRoute = AppDistributorsRouteImport.update({
  id: '/distributors',
  path: '/distributors',
  getParentRoute: () => AppRoute,
} as any)
const AppDistributionRoute = AppDistributionRouteImport.update({
  id: '/distribution',
  path: '/distribution',
  getParentRoute: () => AppRoute,
} as any)
const AppComplianceRoute = AppComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetsRoute = AppBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsRoute = AppAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIdRoute = AppProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/crew': typeof CrewRouteWithChildren
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/app/activity': typeof AppActivityRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/assets': typeof AppAssetsRoute
  '/app/budgets': typeof AppBudgetsRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/distribution': typeof AppDistributionRoute
  '/app/distributors': typeof AppDistributorsRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/financiers': typeof AppFinanciersRoute
  '/app/producers': typeof AppProducersRoute
  '/app/projects': typeof AppProjectsRouteWithChildren
  '/app/reports': typeof AppReportsRoute
  '/app/revenue': typeof AppRevenueRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/app/windows': typeof AppWindowsRoute
  '/crew/schedule': typeof CrewScheduleRoute
  '/app/': typeof AppIndexRoute
  '/crew/': typeof CrewIndexRoute
  '/app/projects/$id': typeof AppProjectsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/app/activity': typeof AppActivityRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/assets': typeof AppAssetsRoute
  '/app/budgets': typeof AppBudgetsRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/distribution': typeof AppDistributionRoute
  '/app/distributors': typeof AppDistributorsRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/financiers': typeof AppFinanciersRoute
  '/app/producers': typeof AppProducersRoute
  '/app/projects': typeof AppProjectsRouteWithChildren
  '/app/reports': typeof AppReportsRoute
  '/app/revenue': typeof AppRevenueRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/app/windows': typeof AppWindowsRoute
  '/crew/schedule': typeof CrewScheduleRoute
  '/app': typeof AppIndexRoute
  '/crew': typeof CrewIndexRoute
  '/app/projects/$id': typeof AppProjectsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/crew': typeof CrewRouteWithChildren
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/app/activity': typeof AppActivityRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/assets': typeof AppAssetsRoute
  '/app/budgets': typeof AppBudgetsRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/distribution': typeof AppDistributionRoute
  '/app/distributors': typeof AppDistributorsRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/financiers': typeof AppFinanciersRoute
  '/app/producers': typeof AppProducersRoute
  '/app/projects': typeof AppProjectsRouteWithChildren
  '/app/reports': typeof AppReportsRoute
  '/app/revenue': typeof AppRevenueRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/app/windows': typeof AppWindowsRoute
  '/crew/schedule': typeof CrewScheduleRoute
  '/app/': typeof AppIndexRoute
  '/crew/': typeof CrewIndexRoute
  '/app/projects/$id': typeof AppProjectsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/contact'
    | '/crew'
    | '/features'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/app/activity'
    | '/app/analytics'
    | '/app/assets'
    | '/app/budgets'
    | '/app/compliance'
    | '/app/distribution'
    | '/app/distributors'
    | '/app/expenses'
    | '/app/financiers'
    | '/app/producers'
    | '/app/projects'
    | '/app/reports'
    | '/app/revenue'
    | '/app/schedule'
    | '/app/settings'
    | '/app/team'
    | '/app/windows'
    | '/crew/schedule'
    | '/app/'
    | '/crew/'
    | '/app/projects/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/features'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/app/activity'
    | '/app/analytics'
    | '/app/assets'
    | '/app/budgets'
    | '/app/compliance'
    | '/app/distribution'
    | '/app/distributors'
    | '/app/expenses'
    | '/app/financiers'
    | '/app/producers'
    | '/app/projects'
    | '/app/reports'
    | '/app/revenue'
    | '/app/schedule'
    | '/app/settings'
    | '/app/team'
    | '/app/windows'
    | '/crew/schedule'
    | '/app'
    | '/crew'
    | '/app/projects/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/contact'
    | '/crew'
    | '/features'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/app/activity'
    | '/app/analytics'
    | '/app/assets'
    | '/app/budgets'
    | '/app/compliance'
    | '/app/distribution'
    | '/app/distributors'
    | '/app/expenses'
    | '/app/financiers'
    | '/app/producers'
    | '/app/projects'
    | '/app/reports'
    | '/app/revenue'
    | '/app/schedule'
    | '/app/settings'
    | '/app/team'
    | '/app/windows'
    | '/crew/schedule'
    | '/app/'
    | '/crew/'
    | '/app/projects/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRouteWithChildren
  ContactRoute: typeof ContactRoute
  CrewRoute: typeof CrewRouteWithChildren
  FeaturesRoute: typeof FeaturesRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crew': {
      id: '/crew'
      path: '/crew'
      fullPath: '/crew'
      preLoaderRoute: typeof CrewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crew/': {
      id: '/crew/'
      path: '/'
      fullPath: '/crew/'
      preLoaderRoute: typeof CrewIndexRouteImport
      parentRoute: typeof CrewRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/crew/schedule': {
      id: '/crew/schedule'
      path: '/schedule'
      fullPath: '/crew/schedule'
      preLoaderRoute: typeof CrewScheduleRouteImport
      parentRoute: typeof CrewRoute
    }
    '/app/windows': {
      id: '/app/windows'
      path: '/windows'
      fullPath: '/app/windows'
      preLoaderRoute: typeof AppWindowsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/team': {
      id: '/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/schedule': {
      id: '/app/schedule'
      path: '/schedule'
      fullPath: '/app/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/revenue': {
      id: '/app/revenue'
      path: '/revenue'
      fullPath: '/app/revenue'
      preLoaderRoute: typeof AppRevenueRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/producers': {
      id: '/app/producers'
      path: '/producers'
      fullPath: '/app/producers'
      preLoaderRoute: typeof AppProducersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financiers': {
      id: '/app/financiers'
      path: '/financiers'
      fullPath: '/app/financiers'
      preLoaderRoute: typeof AppFinanciersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/expenses': {
      id: '/app/expenses'
      path: '/expenses'
      fullPath: '/app/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/distributors': {
      id: '/app/distributors'
      path: '/distributors'
      fullPath: '/app/distributors'
      preLoaderRoute: typeof AppDistributorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/distribution': {
      id: '/app/distribution'
      path: '/distribution'
      fullPath: '/app/distribution'
      preLoaderRoute: typeof AppDistributionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compliance': {
      id: '/app/compliance'
      path: '/compliance'
      fullPath: '/app/compliance'
      preLoaderRoute: typeof AppComplianceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/budgets': {
      id: '/app/budgets'
      path: '/budgets'
      fullPath: '/app/budgets'
      preLoaderRoute: typeof AppBudgetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assets': {
      id: '/app/assets'
      path: '/assets'
      fullPath: '/app/assets'
      preLoaderRoute: typeof AppAssetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects/$id': {
      id: '/app/projects/$id'
      path: '/$id'
      fullPath: '/app/projects/$id'
      preLoaderRoute: typeof AppProjectsIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
  }
}

interface AppProjectsRouteChildren {
  AppProjectsIdRoute: typeof AppProjectsIdRoute
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsIdRoute: AppProjectsIdRoute,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAssetsRoute: typeof AppAssetsRoute
  AppBudgetsRoute: typeof AppBudgetsRoute
  AppComplianceRoute: typeof AppComplianceRoute
  AppDistributionRoute: typeof AppDistributionRoute
  AppDistributorsRoute: typeof AppDistributorsRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppFinanciersRoute: typeof AppFinanciersRoute
  AppProducersRoute: typeof AppProducersRoute
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppReportsRoute: typeof AppReportsRoute
  AppRevenueRoute: typeof AppRevenueRoute
  AppScheduleRoute: typeof AppScheduleRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppWindowsRoute: typeof AppWindowsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAssetsRoute: AppAssetsRoute,
  AppBudgetsRoute: AppBudgetsRoute,
  AppComplianceRoute: AppComplianceRoute,
  AppDistributionRoute: AppDistributionRoute,
  AppDistributorsRoute: AppDistributorsRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppFinanciersRoute: AppFinanciersRoute,
  AppProducersRoute: AppProducersRoute,
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppReportsRoute: AppReportsRoute,
  AppRevenueRoute: AppRevenueRoute,
  AppScheduleRoute: AppScheduleRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTeamRoute: AppTeamRoute,
  AppWindowsRoute: AppWindowsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface CrewRouteChildren {
  CrewScheduleRoute: typeof CrewScheduleRoute
  CrewIndexRoute: typeof CrewIndexRoute
}

const CrewRouteChildren: CrewRouteChildren = {
  CrewScheduleRoute: CrewScheduleRoute,
  CrewIndexRoute: CrewIndexRoute,
}

const CrewRouteWithChildren = CrewRoute._addFileChildren(CrewRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRouteWithChildren,
  ContactRoute: ContactRoute,
  CrewRoute: CrewRouteWithChildren,
  FeaturesRoute: FeaturesRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
